[RS-1] Add metadata matcher script
diging/utilities pull request #3
Opened 2021-02-19 21:36 UTC by nowke

Story - https://diging.atlassian.net/browse/RS-1
Pull request moved from https://github.com/diging/amphora-ipython-notebooks/pull/10

2021-02-24 19:28 UTC, jdamerow requested changes
This will be great! Just a few smallish things :)

2021-02-24 19:28 UTC, jdamerow commented on metadata-matcher/README.md
> +* `METADATA_FILE` - Path to journal metadata file: supports `.xlsx` and `.csv` files
I think this should be "Path to article metadata..."

2021-02-24 19:28 UTC, jdamerow commented on metadata-matcher/README.md
> +* Set the `FLAG_USE_ABSTRACT = True` for including the ***abstract*** column in the matching process.
Let's end all sentences with a `.`

2021-02-24 19:28 UTC, jdamerow commented on metadata-matcher/README.md
> +    * Use `META_AUTHOR_SINGLE_SEPARATOR` to set the separator character
the separator of what?

2021-02-24 19:28 UTC, jdamerow commented on metadata-matcher/README.md
> +2. Authors are listed in multiple column.
should be "... multiple columns" (s is missing)

2021-02-24 19:28 UTC, jdamerow commented on metadata-matcher/README.md
> +* The script overwrites the `FOUND_METADATA` file on every match. You can interrupt the program at any point.
"... at any point by pressing control-C." (?)

2021-02-24 19:28 UTC, jdamerow commented on metadata-matcher/README.md
> +
Maybe add a sentence about how to restart the process.

2021-02-24 19:28 UTC, jdamerow commented on metadata-matcher/README.md
> +The current scoring schema is as follows:
Maybe say another sentence about what that means, e.g. title matches exactly? Authors match completely, just last names,...?

2021-02-24 19:28 UTC, jdamerow commented on metadata-matcher/README.md
> +    * Set `META_AUTHOR_SINGLE_FIELD = False` for this case
Maybe put it how the limit works here (only first 10 columns are used, can be changed in config).

2021-02-24 19:28 UTC, jdamerow commented on metadata-matcher/README.md
> +After setting all configurations in `config.py`, run the following command:
Let's add from where the script should be run (in relation to metadata file and text files).

2021-02-24 19:28 UTC, jdamerow commented on metadata-matcher/run_script.py
> +                        self._found_match(text_file, article_meta, score)
what happens to the article that was previously matched? shouldn't that go into the not matched folder or matched again with the rest of the article metadata?

2021-02-24 19:28 UTC, jdamerow commented on metadata-matcher/run_script.py
> +    journal = Journal(config=config)
journal is a bit of a misleading name I think. Doesn't the data come from all kinds of journals (not just one)?

2021-02-24 19:28 UTC, jdamerow commented on metadata-matcher/run_script.py
> +    journal.search()
similar here, it's not really searching, it's matching, isn't it?

2021-02-24 22:28 UTC, nowke commented on metadata-matcher/README.md
> +After setting all configurations in `config.py`, run the following command:
The script can be run from anywhere. The configs `DIRECTORY`, `METADATA_FILE` accepts both relative and absolute paths.

2021-02-25 18:19 UTC, jdamerow commented on metadata-matcher/README.md
> +After setting all configurations in `config.py`, run the following command:
Then it should say that.

2021-02-25 18:20 UTC, jdamerow commented on metadata-matcher/README.md
> +
add what to do to restart the process from the beginning.

2021-02-26 20:17 UTC, nowke commented on metadata-matcher/README.md
> +After setting all configurations in `config.py`, run the following command:
`DIRECTORY` takes absolute and relative path. Rest of the paths are relative to `DIRECTORY` (https://github.com/diging/amphora-ipython-notebooks/pull/10/files/016412dea4956245be9c183e148f3c8aad5a4766#r574679521)

Indicated the same.

2021-02-26 20:17 UTC, nowke commented on metadata-matcher/run_script.py
> +    journal = Journal(config=config)
Changed to `MetadataEntries`

2021-02-26 20:18 UTC, nowke commented on metadata-matcher/run_script.py
> +    journal.search()
Renamed to `match`

2021-03-05 15:52 UTC, tjquinn1 approved these changes

2021-03-05 15:52 UTC, tjquinn1 commented on metadata-matcher/README.md
> +
This has been taken care of now, right?

2021-03-05 16:20 UTC, jdamerow requested changes
Just these two little things and should be good to go! Let's send the link to Ken.

2021-03-05 16:20 UTC, jdamerow commented on metadata-matcher/README.md
> +* `DIRECTORY` - Path to the parent folder containing all relevant files. Accepts both relative (to where the script is run from), and absolute path.
"all relevant files" means text files that contain the article texts for the articles in the metadata file, right? Someone who is not Ken or us won't know that.

2021-03-05 16:20 UTC, jdamerow commented on metadata-matcher/README.md
> +This script is used for matching journal articles and metadata. Requires Python 3.6+.
I would add one more sentence that explains how this works/what is required, since people who are not Ken or us won't know that. 
eg:
"This script will match metadata entries of articles in a csv or xlsx file with plain text files containing the content of the articles listed in the metadata file. It does so by comparing..."
Something like that.

2021-03-05 16:35 UTC, nowke commented on metadata-matcher/README.md
> +* `DIRECTORY` - Path to the parent folder containing all relevant files. Accepts both relative (to where the script is run from), and absolute path.
Yes. Fixed

2021-03-05 16:36 UTC, nowke commented on metadata-matcher/README.md
> +This script is used for matching journal articles and metadata. Requires Python 3.6+.
Added a couple of more sentences.

2021-03-05 17:12 UTC, merged